# EmissionML Discussion Paper

OGC doc number 25-023

Draft is available for comments now: https://github.com/opengeospatial/EmissionML/blob/25-023/document.pdf 

This repository contains the content for the OGC EmissionML Discussion Paper.

* `document.adoc` - the main standard document with references to all sections
* remaining ``adoc``s - each section of the standard document is in a separate document: follow directions in each document to populate
* `figures` - figures go here
* `images` - Image files for graphics go here. Image files for figures go in the `figures` directory. Only place in here images not used in figures (e.g., as parts of tables, as logos, etc.)
* `requirements` - directory for requirements and requirement classes to be referenced in `clause_7_normative_text.adoc`
* `code` - sample code to accompany the standard, if desired
* `abstract_tests` - the Abstract Test Suite comprising one test for every requirement, optional
* `UML` - UML diagrams, if applicable

== Building in MacOS
```bash
metanorma compile -t ogc document.adoc
```

More about Metanorma: https://www.metanorma.org/author/ogc/
