name: docker

on:
  push:
    branches: [ master, main, 25-019 ]
  pull_request:
    paths-ignore:
      - .gitlab-ci.yml
      - .github/workflows/test.yml
      - .github/workflows/generate.yml
  repository_dispatch:
    types: [ metanorma/metanorma-docker ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test-docker:
    runs-on: ubuntu-latest
    container: docker://metanorma/mn
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions-mn/build-and-publish@v1
        with:
          agree-to-terms: true
          use-bundler: true
          destination: artifact
          artifact-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-docker
