name: generate

on:
  push:
    branches: [ master, main, 25-019 ]
  pull_request:
    paths-ignore:
      - .gitlab-ci.yml
      - .github/workflows/test.yml
      - .github/workflows/docker.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  site-generate:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions-mn/setup@main

      - uses: actions-mn/build-and-publish@v1
        with:
          agree-to-terms: true
          use-bundler: true
          destination: artifact
          artifact-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ matrix.os }}
